backend:
  name: github
  repo: Varun-Krishna-P/ss
  branch: main

media_folder: "static/media"
public_folder: "public"

# media_library:
#   name: uploadcare

collections:
  - name: "Contact Us"
    label: "Contact us"
    files: 
      - label: "Contact"
        name: "Contact" 
        file: "src/components/ContactUs.tsx"
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "text" }
          - { label: "Website", name: "website", widget: "string" }

    create: true    
  - name: "media"
    label: "Media"
    folder: "static/uploads"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Image", name: "image", widget: "image" }