local_backend: true
backend:
  name: github
  repo: Varun-Krishna-P/ss
  branch: main

media_folder: "static/media"
public_folder: "public"

# media_library:
#   name: uploadcare

collections:
  - name: "Contact Us"
    label: "Contact us"
    files: 
      - label: "Contact"
        name: "Contact" 
        file: "src/components/ContactUs.tsx"
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "text" }
          - { label: "Website", name: "website", widget: "string" }

    create: true    
  - name: "image"
    label: "Image"
    extension: "yml"
    folder: "static/uploads/images"
    media_folder: "/static/media/images"
    public_folder: "/media/images"
    create: true
    slug: "{{fields.title}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
  - name: "Catalog"
    label: "Catalog"
    folder: "/src/data/catalog"
    extension: "yml"
    format: "yml"
    create: true
    slug: "{{fields.short_name}}"
    identifier_field: short_name
    summary: "{{fields.name}} ({{fields.short_name}})"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Short Name", name: "short_name", widget: "string" }
      - { label: "Image Path", name: "image_path", widget: "string" }