local_backend: true
backend:
  name: github
  repo: Varun-Krishna-P/ss
  branch: main

media_folder: "static/media"
public_folder: "public"

# media_library:
#   name: uploadcare

collections:
  - name: "app_config"
    label: "App Configuration"
    files:
      - label: "App Config"
        name: "app_config"
        file: "src/data/app_config/app_config.yml"
        extension: "yml"
        fields:
          - name: "app_config"
            label: "App Config"
            widget: "object"
            fields:
              - { label: "Site Name", name: "site_name", widget: "string" }
              - { label: "Tagline", name: "tagline", widget: "string" }
  - name: "Contact Us"
    label: "Contact us"
    files:
      - label: "Contact"
        name: "Contact"
        file: "src/data/contact/contact.yml"
        extension: "yml"
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "text" }
          - { label: "Website", name: "website", widget: "string" }

    create: true
  - name: "image"
    label: "Image"
    extension: "yml"
    folder: "static/uploads/images"
    media_folder: "/static/media/images"
    public_folder: "/media/images"
    create: true
    slug: "{{fields.title}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
  - name: "Catalog"
    label: "Catalog"
    folder: "/src/data/catalog"
    extension: "yml"
    format: "yml"
    create: true
    slug: "{{fields.short_name}}"
    identifier_field: short_name
    summary: "{{fields.name}} ({{fields.short_name}})"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Short Name", name: "short_name", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - {
          label: "Upload Image",
          name: "image_path",
          widget: "image",
          media_folder: "/static/media/images",
          public_folder: "/media/images",
        }
      - { label: "Benefits", name: "benefits", widget: "markdown", required: false }
      - { label: "Price Details", name: "price", widget: "string", required: false }
      - { label: "Archive Course", name: "is_archived", widget: "boolean", default: false, required: false }
  - name: "Payment"
    label: "Payment"
    files:
      - label: "Payment Config"
        name: "payment_config"
        file: "src/data/payment/payment.yaml"
        extension: "yaml"
        fields:
          - { label: "Per Class Fee", name: "perClass", widget: "number" }
          - { label: "Ten Class Fee", name: "tenClass", widget: "number" }
          - { label: "Per Month Fee", name: "perMonth", widget: "number" }
